# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: name-tests-test
        args: [--pytest-test-first]
    -   id: check-ast
    -   id: check-case-conflict
-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        args:
          - --line-length=88
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
        name: "isort (python)"
        types: [python]
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.20.0
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate
      args: [-vv, -i, --fail-under=50]
